services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: deepresearch
      POSTGRES_PASSWORD: deepresearch
      POSTGRES_DB: deepresearch
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
