{{- if or .Values.env.authToken (and (eq .Values.env.storage "postgres") .Values.env.postgresUrl) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deepresearch-gui.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "deepresearch-gui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.env.authToken }}
  gui-auth-token: {{ .Values.env.authToken | b64enc }}
  {{- end }}
  {{- if and (eq .Values.env.storage "postgres") .Values.env.postgresUrl }}
  gui-postgres-url: {{ .Values.env.postgresUrl | b64enc }}
  {{- end }}
{{- end -}}
