version: "3.9"

services:
  gui:
    image: deepresearch-gui:latest
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://api:8080
    depends_on:
      - api
  api:
    image: deepresearch-api:latest
    environment:
      RUST_LOG: info
    ports:
      - "8080:8080"
    depends_on:
      - qdrant
      - postgres
