global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-gateway:9464']
    metrics_path: /metrics

rule_files:
  - alerts/sandbox_alerts.yml
