name: Evaluation Harness Weekly

on:
  schedule:
    - cron: "0 4 * * 1" # Mondays at 04:00 UTC
  workflow_dispatch:

jobs:
  replay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-eval-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Find latest snapshot
        id: snapshot
        run: |
          SNAPSHOT=$(ls -1 data/pipeline/curated/sessions_*.json | sort | tail -n 1)
          if [ -z "$SNAPSHOT" ]; then
            echo "No curated snapshot found" >&2
            exit 1
          fi
          echo "snapshot=$SNAPSHOT" >> $GITHUB_OUTPUT

      - name: Run evaluation harness
        env:
          SNAPSHOT: ${{ steps.snapshot.outputs.snapshot }}
        run: |
          cargo run -p eval-harness -- \
            --input "$SNAPSHOT" \
            --output-dir data/eval/latest \
            --limit 100 \
            --max-verdict-delta 0 \
            --bootstrap-samples 2000 \
            --batch-size 200 \
            --delta-sample-limit 250

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-report
          path: |
            data/eval/latest/report.json
            data/eval/latest/report.md
            data/eval/latest/dashboard.html
            data/eval/latest/deltas/
          if-no-files-found: error
